class Question:
    def __init__(self, question, options, correct_answer, difficulty):
        self.question = question
        self.options = options
        self.correct_answer = correct_answer
        self.difficulty = difficulty

questions_tree = {
    'easy': [
        Question("Which planet is known as the Red Planet?", ["Mars", "Venus", "Jupiter", "Saturn"], "Mars", "easy"),
        Question("What is 8 × 4?", ["28", "32", "36", "40"], "32", "easy"),
        Question("What is the largest mammal?", ["Blue Whale", "Elephant", "Giraffe", "Shark"], "Blue Whale", "easy"),
        Question("What color do you get when you mix red and white?", ["Pink", "Purple", "Orange", "Yellow"], "Pink", "easy"),
        Question("What is the boiling point of water?", ["100°C", "90°C", "80°C", "110°C"], "100°C", "easy"),
        Question("How many continents are there?", ["5", "6", "7", "8"], "7", "easy"),
        Question("What is 5 + 5?", ["10", "11", "12", "13"], "10", "easy"),
        Question("Which animal is known as the King of the Jungle?", ["Lion", "Tiger", "Elephant", "Bear"], "Lion", "easy"),
        Question("What is the smallest planet in our solar system?", ["Mercury", "Mars", "Venus", "Earth"], "Mercury", "easy"),
        Question("What is the main ingredient in guacamole?", ["Avocado", "Tomato", "Onion", "Pepper"], "Avocado", "easy"),
        Question("Which shape has four equal sides?", ["Square", "Rectangle", "Triangle", "Circle"], "Square", "easy"),
        Question("How many days are in a leap year?", ["366", "365", "364", "367"], "366", "easy"),
        Question("Which fruit is known for having its seeds on the outside?", ["Strawberry", "Blueberry", "Blackberry", "Raspberry"], "Strawberry", "easy"),
        Question("What is the largest ocean on Earth?", ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"], "Pacific Ocean", "easy"),
        Question("What instrument is used to measure temperature?", ["Thermometer", "Barometer", "Hygrometer", "Altimeter"], "Thermometer", "easy"),
        Question("What is the chemical formula for water?", ["H2O", "CO2", "O2", "H2O2"], "H2O", "easy"),
        Question("What is the capital of Japan?", ["Tokyo", "Seoul", "Beijing", "Bangkok"], "Tokyo", "easy"),
        Question("What is the main language spoken in Spain?", ["Spanish", "French", "Italian", "Portuguese"], "Spanish", "easy"),
        Question("What do bees collect from flowers?", ["Nectar", "Pollen", "Honey", "Sugar"], "Nectar", "easy"),
        Question("Which planet is known for its rings?", ["Saturn", "Jupiter", "Neptune", "Mars"], "Saturn", "easy"),
        Question("What is the color of the sky on a clear day?", ["Blue", "Green", "Red", "Yellow"], "Blue", "easy"),
        Question("Which fruit is known as the King of Fruits?", ["Mango", "Durian", "Banana", "Apple"], "Durian", "easy"),
        Question("How many legs does a spider have?", ["6", "8", "10", "12"], "8", "easy"),
        Question("Which animal is known for its ability to change colors?", ["Chameleon", "Octopus", "Snake", "Frog"], "Chameleon", "easy"),
        Question("What is the main language spoken in China?", ["Chinese", "English", "Spanish", "French"], "Chinese", "easy"),
        Question("What is the largest planet in our solar system?", ["Jupiter", "Saturn", "Earth", "Mars"], "Jupiter", "easy"),
        Question("What is the capital of the USA?", ["Washington D.C.", "New York", "Los Angeles", "Chicago"], "Washington D.C.", "easy"),
        Question("Which is the smallest continent?", ["Australia", "Antarctica", "Europe", "South America"], "Australia", "easy"),
        Question("What is 10 ÷ 2?", ["4", "5", "6", "7"], "5", "easy"),
        Question("Which season comes after summer?", ["Winter", "Spring", "Autumn", "Fall"], "Autumn", "easy"),
        Question("What do you call a baby cat?", ["Kitten", "Puppy", "Cub", "Fawn"], "Kitten", "easy"),
        Question("What is the hardest natural mineral?", ["Diamond", "Ruby", "Sapphire", "Emerald"], "Diamond", "easy"),
        Question("Which gas do humans breathe in?", ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], "Oxygen", "easy"),
        Question("What is the main ingredient in bread?", ["Flour", "Sugar", "Water", "Salt"], "Flour", "easy"),
        Question("Which day comes after Monday?", ["Tuesday", "Sunday", "Wednesday", "Thursday"], "Tuesday", "easy"),
        Question("What is 3 × 3?", ["6", "7", "8", "9"], "9", "easy"),
        Question("What do you call a person who studies stars?", ["Astronomer", "Geologist", "Biologist", "Meteorologist"], "Astronomer", "easy"),
        Question("How many colors are there in a rainbow?", ["5", "6", "7", "8"], "7", "easy"),
        Question("What is the largest land animal?", ["Elephant", "Giraffe", "Rhino", "Hippo"], "Elephant", "easy"),
        Question("What is the main ingredient in chocolate?", ["Cocoa", "Milk", "Sugar", "Vanilla"], "Cocoa", "easy"),
        Question("What is the currency used in Japan?", ["Yen", "Won", "Dollar", "Euro"], "Yen", "easy"),
        Question("What color do you get when you mix red and white?", ["Pink", "Purple", "Orange", "Yellow"], "Pink", "easy"),
          ],
    'medium': [
        Question("Who painted the Mona Lisa?", ["Leonardo da Vinci", "Vincent van Gogh", "Pablo Picasso", "Michelangelo"], "Leonardo da Vinci", "medium"),
        Question("What is the chemical symbol for gold?", ["Au", "Ag", "Fe", "Cu"], "Au", "medium"),
        Question("What is the square root of 144?", ["10", "11", "12", "13"], "12", "medium"),
        Question("Who wrote 'Romeo and Juliet'?", ["William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain"], "William Shakespeare", "medium"),
        Question("What is the hardest natural substance on Earth?", ["Diamond", "Gold", "Iron", "Quartz"], "Diamond", "medium"),
        Question("What gas do plants absorb from the atmosphere?", ["Carbon Dioxide", "Oxygen", "Nitrogen", "Hydrogen"], "Carbon Dioxide", "medium"),
        Question("What is the capital city of Australia?", ["Canberra", "Sydney", "Melbourne", "Brisbane"], "Canberra", "medium"),
        Question("In which year did the Titanic sink?", ["1912", "1905", "1898", "1920"], "1912", "medium"),
        Question("Who invented the telephone?", ["Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Isaac Newton"], "Alexander Graham Bell", "medium"),
        Question("Which planet is the hottest in our solar system?", ["Venus", "Mercury", "Mars", "Jupiter"], "Venus", "medium"),
        Question("What is the capital of Italy?", ["Rome", "Venice", "Milan", "Florence"], "Rome", "medium"),
        Question("What is the largest organ in the human body?", ["Skin", "Liver", "Heart", "Brain"], "Skin", "medium"),
        Question("Which element has the atomic number 1?", ["Hydrogen", "Helium", "Oxygen", "Carbon"], "Hydrogen", "medium"),
        Question("What is the process by which plants make their food called?", ["Photosynthesis", "Respiration", "Transpiration", "Fermentation"], "Photosynthesis", "medium"),
        Question("Which country is known as the Land of the Rising Sun?", ["Japan", "China", "Thailand", "Korea"], "Japan", "medium"),
        Question("What is the main language spoken in Brazil?", ["Portuguese", "Spanish", "English", "French"], "Portuguese", "medium"),
        Question("What is the currency of the United States?", ["Dollar", "Euro", "Yen", "Pound"], "Dollar", "medium"),
        Question("What is the chemical formula for table salt?", ["NaCl", "KCl", "CaCl2", "MgCl2"], "NaCl", "medium"),
        Question("Which country is home to the kangaroo?", ["Australia", "New Zealand", "South Africa", "Canada"], "Australia", "medium"),
        Question("What is the capital of Canada?", ["Ottawa", "Toronto", "Vancouver", "Montreal"], "Ottawa", "medium"),
        Question("Which scientist is known for the laws of motion?", ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Stephen Hawking"], "Isaac Newton", "medium"),
        Question("What is the capital of New Zealand?", ["Wellington", "Auckland", "Christchurch", "Hamilton"], "Wellington", "medium"),
        Question("Who is known for the theory of evolution?", ["Charles Darwin", "Albert Einstein", "Isaac Newton", "Galileo Galilei"], "Charles Darwin", "medium"),
        Question("What is the largest desert in the world?", ["Sahara", "Arabian", "Gobi", "Kalahari"], "Sahara", "medium"),
        Question("In which city is the Statue of Liberty located?", ["New York", "Los Angeles", "Chicago", "Boston"], "New York", "medium"),
        Question("What is the chemical symbol for water?", ["H2O", "CO2", "NaCl", "O2"], "H2O", "medium"),
        Question("Which gas is most abundant in the Earth's atmosphere?", ["Nitrogen", "Oxygen", "Carbon Dioxide", "Argon"], "Nitrogen", "medium"),
        Question("What is the largest continent on Earth?", ["Asia", "Africa", "North America", "Europe"], "Asia", "medium"),
        Question("Who is the author of '1984'?", ["George Orwell", "Aldous Huxley", "Ray Bradbury", "Mark Twain"], "George Orwell", "medium"),
        Question("What is the capital of Brazil?", ["Brasilia", "Rio de Janeiro", "Sao Paulo", "Salvador"], "Brasilia", "medium"),
        Question("What is the primary language spoken in Russia?", ["Russian", "Ukrainian", "Polish", "Kazakh"], "Russian", "medium"),
        Question("What is the currency of the European Union?", ["Euro", "Dollar", "Pound", "Yen"], "Euro", "medium"),
        Question("What is the name of the longest river in Asia?", ["Yangtze", "Ganges", "Indus", "Mekong"], "Yangtze", "medium"),
        Question("What is the boiling point of water at sea level?", ["100°C", "90°C", "80°C", "120°C"], "100°C", "medium"),
        Question("Who painted the Sistine Chapel ceiling?", ["Michelangelo", "Raphael", "Da Vinci", "Botticelli"], "Michelangelo", "medium"),
        Question("What is the most spoken language in the world?", ["Mandarin", "English", "Spanish", "Hindi"], "Mandarin", "medium"),
    ],
    'hard': [
        Question("What is the first law of thermodynamics?", ["Energy cannot be created or destroyed", "Heat flows from cold to hot", "Entropy of an isolated system always increases", "Work done on a system is equal to heat added"], "Energy cannot be created or destroyed", "hard"),
        Question("What is the name of the first artificial satellite?", ["Sputnik 1", "Apollo 11", "Explorer 1", "Voyager 1"], "Sputnik 1", "hard"),
        Question("What is the capital of Egypt?", ["Cairo", "Alexandria", "Giza", "Luxor"], "Cairo", "hard"),
        Question("What is the primary focus of quantum mechanics?", ["Behavior of very small particles", "Motion of planets", "Chemical reactions", "Fluid dynamics"], "Behavior of very small particles", "hard"),
        Question("What is the primary function of red blood cells?", ["Carry oxygen", "Fight infections", "Clot blood", "Regulate body temperature"], "Carry oxygen", "hard"),
        Question("What is the main purpose of a diode in electronics?", ["Allow current to flow in one direction", "Store energy", "Amplify signals", "Convert AC to DC"], "Allow current to flow in one direction", "hard"),
        Question("Who is known as the father of genetics?", ["Gregor Mendel", "Charles Darwin", "Louis Pasteur", "James Watson"], "Gregor Mendel", "hard"),
        Question("What is the term for the change of a substance from a solid to a gas?", ["Sublimation", "Evaporation", "Condensation", "Melting"], "Sublimation", "hard"),
        Question("What is the Pythagorean theorem?", ["a² + b² = c²", "a + b = c", "a - b = c", "a/b = c"], "a² + b² = c²", "hard"),
        Question("What is the primary purpose of the human liver?", ["Detoxification", "Digestion", "Respiration", "Circulation"], "Detoxification", "hard"),
        Question("What is the highest mountain in the world?", ["Mount Everest", "K2", "Kangchenjunga", "Lhotse"], "Mount Everest", "hard"),
        Question("What is the chemical formula for methane?", ["CH4", "CO2", "C2H6", "C3H8"], "CH4", "hard"),
    ]
}

